# Generated by Django 6.0 on 2025-12-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=200)),
                ('os', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('HarmonyOS', 'HarmonyOS'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.brand')),
            ],
            options={
                'verbose_name': 'Mobile Phone',
                'verbose_name_plural': 'Mobile Phones',
                'ordering': ['-created_at'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
    ]
