# Generated by Django 6.0 on 2025-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file (optional if image URL is provided)', null=True, upload_to='phones/'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL (optional if image file is uploaded)', null=True),
        ),
    ]
