# Generated by Django 6.0 on 2025-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Case', 'Phone Case'), ('Charger', 'Charger'), ('Earphones', 'Earphones'), ('Screen Protector', 'Screen Protector'), ('Power Bank', 'Power Bank'), ('Cable', 'Cable'), ('Other', 'Other')], default='Other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ['-created_at'],
            },
        ),
    ]
